#GD-197 state: to verify work 5h
IT-Siberians/LotDesignerMicroservice pull request #1
Opened 2024-09-24 11:37 UTC by Lietuonis

Create domain value objects, documentation, exceptions

2024-09-24 23:43 UTC, m-a-ilnitsky approved these changes
Лучше сделать более информативные namespace содержащие название проекта или микросервиса

2024-09-24 23:43 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +    public abstract class ValueObject<T>
Здесь потребуют добавить Equals и GetHashCode и видимо реализовать IEquatable<>

2024-09-24 23:43 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +﻿namespace Domain.ValueObjects.Base
Имена всех namespace лучше сделать начинающимися либо с имени проекта, либо с имени микросервиса, или и с того и с другого

2024-09-24 23:43 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +﻿namespace Domain.ValueObjects.Base
И само название репозитория LotsDirectoryMicroservice кажется не отражает смысл микросервиса.
Мне кажется что слово Directory больше про каталоги/папки файловой системы.
А здесь должно быть слово Catalog

2024-09-25 08:41 UTC, oleggolen requested changes
В целом достаточно хороший код, но я бы исправил замечания Михаила, ну и дописал бы корректную работу с ValueObject'ами в полной мере

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +﻿namespace Domain.ValueObjects.Base
Согласен полностью

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +    public abstract class ValueObject<T>
Полностью согласен, а также перегрузить операторы == и != как минимум

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +            Validate(value);
Лучше не делать в конструкторе вызовов виртуальных(абстрактных) методов, можно заменить это наследование композицией, как это сделано у коллег

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/PriceHasMoreThanTwoDecimalPlaces.cs
> +        : ArgumentOutOfRangeException("Value", string.Format(PriceResources.PRICE_HAS_MORE_THEN_TWO_DECIMAL_PLACES, value));
Можно сюда ещё передать само значение, чтобы было наглядно

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/PriceLessOrEqualZero.cs
> +        : ArgumentNullException("Value", string.Format(PriceResources.PRICE_LESS_OR_EQUAL_ZERO, value));
Не уверен, что хорошая идея тут ArgumentNullException, скорее подойдёт ArgumentOutOfRange, а также стоит для наглядности передать само значени

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/TitleMaxLenghtException.cs
> +        : ArgumentOutOfRangeException("Value", string.Format(TitleResources.TITLE_MAX_LENGHT_EXCEPTION, valueLength, TitleResources.TITLE_MAX_LENGTH));
Также стоит передать информацию о корректном диапозоне длины

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/UserNameMaxLenghtException.cs
> +}
Также стоит передать информацию о корректном диапозоне длины

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +                throw new PriceHasMoreThanTwoDecimalPlaces(value);
Кстати очень крутое решение, не знал, что так вообще возможно, можно Яне посоветовать и Михаилу

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Title.cs
> +                throw new TitleMaxLenghtException(value.Length);
Здесь не имеет смысла конструкция if...else if, так как бросание исключения прерывает само по себе исполнение метода

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +    public sealed class Price(decimal value) : ValueObject<decimal>(value)
Здесь бы в конструкторе я бы тоже округлял бы до двух знаком после запятой, потому что возможно в дальшейшей логике приложения нам придётся совершать арифметические операции с ценой лота(хотя возможно это только в сервисе торогов), а в результате операций с вещественными числами иногда появляются так называемые "шумы", которые будут кидать исключения либо вообще игнорироваться и со временем накапливаться

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/UserName.cs
> +                throw new UserNameMaxLenghtException(value.Length);
Здесь тоже конструкция if...else if не имеет смысла, так как бросание исключения само по себе прерывает работу метода

2024-09-25 08:41 UTC, oleggolen commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +    public sealed class Price(decimal value) : ValueObject<decimal>(value)
Также тут ещё нужно дописать арифместические операции сравнения: больше, меньще - и арифметичекие операции сложения, вычетания

2024-09-25 11:34 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +    public sealed class Price(decimal value) : ValueObject<decimal>(value)
Мне кажется именно Илье операции сложения/вычитания можно не реализовывать, т.к. у него они вроде нигде не будут использоваться

2024-09-25 11:40 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +    public sealed class Price(decimal value) : ValueObject<decimal>(value)
И если делать округление в конструкторе, то можно не делать в валидации поверку на количество знаков

2024-09-25 11:45 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/TitleMaxLenghtException.cs
> +        : ArgumentOutOfRangeException("Value", string.Format(TitleResources.TITLE_MAX_LENGHT_EXCEPTION, valueLength, TitleResources.TITLE_MAX_LENGTH));
Здесь видимо идёт речь о проверке и выводе еще и минимальной длины заголовка.
Тогда эти значения мин/макс для длин строк всех объектов значений лучше посмотреть у меня и Яны и сделать такие же ограничения

2024-09-25 12:15 UTC, ConstantinProg commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +﻿namespace Domain.ValueObjects.Base
Осмелюсь предложить ещё LotDesignerMicroservice или LotBuilderMicroservice.

2024-09-25 14:51 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Base/ValueObject.cs
> +﻿namespace Domain.ValueObjects.Base
Да, варианты Константина мне нравятся даже больше.
А то с самого начала название этого микросервиса даже на русском казалось немного непонятным

2024-09-25 20:38 UTC, Lietuonis commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +    public sealed class Price(decimal value) : ValueObject<decimal>(value)
Идея была именно в том, что в этом микросервисе никаких операций с деньгами быть не может, мы только жёстко задаём начальную цену и её шаг. Если заданы новые значения, то они просто перезапишутся. Но идея с округлением в конструкторе неплохая, позволит избежать потенциальных проблем с формами ввода значения. Валидацию в таком случае действительно можно убрать, но я бы предпочёл оставить, чтобы легче отловить ошибки округления, если такое случится

2024-09-25 20:39 UTC, Lietuonis commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +                throw new PriceHasMoreThanTwoDecimalPlaces(value);
@m-a-ilnitsky @Yana-Kryukova делюсь вариантом

2024-09-25 20:42 UTC, Lietuonis commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/TitleMaxLenghtException.cs
> +        : ArgumentOutOfRangeException("Value", string.Format(TitleResources.TITLE_MAX_LENGHT_EXCEPTION, valueLength, TitleResources.TITLE_MAX_LENGTH));
@m-a-ilnitsky брал значение максимальной длины как раз у Яны
@oleggolen в string.Format передаётся текущая длина и максимально доступная длина, после чего из этих значений и собирается сообщение ошибки. Если есть варианты изящнее, буду рад идеям

2024-09-25 20:43 UTC, Lietuonis commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/PriceLessOrEqualZero.cs
> +        : ArgumentNullException("Value", string.Format(PriceResources.PRICE_LESS_OR_EQUAL_ZERO, value));
@oleggolen тип исключения изменю, а само значение передаётся в string.Format

2024-09-25 20:44 UTC, Lietuonis commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/UserNameMaxLenghtException.cs
> +}
@oleggolen в string.Format передаётся текущая длина и максимально доступная длина, после чего из этих значений и собирается сообщение ошибки

2024-09-25 20:44 UTC, Lietuonis commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/PriceHasMoreThanTwoDecimalPlaces.cs
> +        : ArgumentOutOfRangeException("Value", string.Format(PriceResources.PRICE_HAS_MORE_THEN_TWO_DECIMAL_PLACES, value));
@oleggolen аналогично, передаётся в string.Format

2024-09-26 00:06 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/Exceptions/TitleMaxLenghtException.cs
> +        : ArgumentOutOfRangeException("Value", string.Format(TitleResources.TITLE_MAX_LENGHT_EXCEPTION, valueLength, TitleResources.TITLE_MAX_LENGTH));
@Lietuonis Не помню как у Яны, но я задавал и верхнюю и нижнюю границу длины, т.к. очевидно, что заголовок не должен состоять из 1 или двух символов.
Думаю Олег предлагал добавить именно нижнюю границу длины.
Но лучше переспросить у него))

2024-09-26 00:11 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +    public sealed class Price(decimal value) : ValueObject<decimal>(value)
Не понял идею валидировать наличие двух знаков и округлять до двух знаков одновременно.
Если валидация выбросит округление то округлять будет нечего.
А если будет отдельный метод валидации который можно вызвать вне конструктора, то будет плохо, если этот метод будет забраковывать значения которые конструктор спокойно пережёвывает (округляет)

2024-09-26 00:16 UTC, m-a-ilnitsky commented on LotsDirectoryMicroservice/Domain/Domain.ValueObjects/ValueObjects/Price.cs
> +                throw new PriceHasMoreThanTwoDecimalPlaces(value);
Я думаю, что такая проверка имеет право на жизнь, если нет округления в конструкторе.
Но с округлением она несовместима

2024-10-04 13:21 UTC, oleggolen approved these changes
По мне вроде бы всё нормально, но очень много лишнего всякого, и как можно больше в домене убрать nullable всякие разные, а так выглядит нормально

2024-10-04 13:21 UTC, oleggolen commented on LotDesignerMicroservice/Domain/ValueObjects/NumericObjects/Price.cs
> +        public override decimal? MAX_VALUE => null;
Уж очень я не люблю nullable значения на границах интервалов да и вообще где-либо, не должно быть оно так. тем более можно взять какие-то разумные ограничения

2024-10-04 13:21 UTC, oleggolen commented on LotDesignerMicroservice/Domain/ValueObjects/NumericObjects/Price.cs
> +        }
Зачем здесь этот метод?

2024-10-04 13:21 UTC, oleggolen commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/StringObject.cs
> +        public abstract int? MAX_LENGHT { get; }
Ограничения не должны быть nullable

2024-10-04 13:21 UTC, oleggolen commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/NumericObject.cs
> +        public abstract T? MAX_VALUE { get; }
Не должны быть ограничения nullable

2024-10-04 13:21 UTC, oleggolen commented on LotDesignerMicroservice/Domain/ValueObjects/StringObjects/Text.cs
> +        }
Зачем этот метод?

2024-10-04 13:21 UTC, oleggolen commented on LotDesignerMicroservice/Domain/ValueObjects/StringObjects/Title.cs
> +        }
Зачем этот метод?

2024-10-04 13:21 UTC, oleggolen commented on LotDesignerMicroservice/Domain/ValueObjects/StringObjects/UserName.cs
> +        }
Зачем этот метод?

2024-10-04 15:55 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/NumericObject.cs
> +        where T : struct, INumber<T>
Не хватает интерфейса IEqualityOperators

2024-10-08 15:54 UTC, NikeTorchwood approved these changes
согласно патенту

2024-10-08 18:59 UTC, m-a-ilnitsky approved these changes

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/NumericObject.cs
> +        public abstract T MAX_VALUE { get; }
Не могу понять какой смысл здесь играет слово abstract.
Такое ощущение, что без него будет то же самое

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/NumericObject.cs
> +        public NumericObject(T value, Action<T>? validate = null) : base(value, validate)
Конструктор абстрактного класса лучше сделать protected

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/StringObject.cs
> +        public StringObject(string value, Action<string>? validate = null) : base(value, validate)
Аналогично про protected

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/ValueObject.cs
> +        public ValueObject(T value, Action<T>? validate = null)
Аналогично про protected

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/ValueObject.cs
> +            Value = value;
На мой взгляд немного нелогично, что сначала в базовом классе свойству Value присваивается значение, а потом в классах наследниках выполняется дополнительная валидация и бросается исключение (уже после присваивания значения).
Хотя конечно есть в этом варианте некоторое удобство..

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/ValueObject.cs
> +        public T Value { get; protected set; }
Можно убрать "protected set;" и округление Price(decimal value) подставить в вызов базового конструктора.
Сейчас получается что Price значение присваивается 2 раза, сначала исходное в самом базовом конструкторе, а потом округлённое в самом внешнем, это выглядит не очень очевидно.
Мне кажется будет проще для понимания, если значение будет присваиваться в одном месте.
Хотя конечно тогда округление будет выполняться всегда, а не только по необходимости

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/ValueObject.cs
> +            }
Лучше еще добавить стандартную проверку на равенство ссылок

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/DateTimeObjects/TradeDuration.cs
> +    public sealed class TradeDuration(TimeSpan value) : ValueObject<TimeSpan>(value, Validate)
Возможно лучше назвать TradingDuration, но не уверен

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/DateTimeObjects/TradeDuration.cs
> +        private static void Validate(TimeSpan value)
Сейчас получается, что часть проверок выполняется в конструкторах разного уровня, а часть в валидаторах (Validate).
Думаю будет проще для понимания если сделать все проверки единообразно

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/StringObjects/UserName.cs
> +    public sealed class UserName(string value) : StringObject(value)
Для единообразия, лучше назвать Username (одним словом), как сделано во всех остальных микросервисах

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/NumericObject.cs
> +        public abstract T MAX_VALUE { get; }
В итоге, посмотрев весь код, я понял зачем здесь здесь abstract.
Возможно virtual было бы очевиднее, но наверное abstract действительно здесь больше подходит

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/NumericObject.cs
> +        public abstract T MAX_VALUE { get; }
Тут исходно казалось, что этим свойствам в конструкторе класса-наследника будет просто присвоено значение и тогда abstract не нужен.
Тот факт, что для того чтобы заполнить эти свойства значениями в классе-наследнике до вызова конструктора базового класса приходится использовать инициализаторы полей класса-наследника выглядит не очень то очевидно))

2024-10-08 18:59 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/ValueObject.cs
> +                validate(value);
Студия предлагает заменить это на: validate?.Invoke(value);

2024-10-09 06:48 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/StringObjects/Text.cs
> +        public override int MAX_LENGHT => 20000;
Мне кажется для таких длинных строк нет особого смысла делать ограничение по длине.
Думаю текст описания лучше хранить в базе в типе text у которого нет фактического ограничения длины

2024-10-09 06:52 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/NumericObjects/Price.cs
> +        public override decimal MAX_VALUE => 300000;
Думаю для цен не стоит делать ограничение на уровне ValueObject.
Здесь мне кажется достаточно ограничения, что цена должна быть точно больше 0.
Остальное скорее всего должно решаться на более высоком уровне.
А верхнюю границу думаю вообще не стоит задавать

2024-10-11 02:52 UTC, m-a-ilnitsky commented on LotDesignerMicroservice/Domain/ValueObjects/BaseObjects/NumericObject.cs
> +        public abstract T MAX_VALUE { get; }
И еще такой момент...
Сейчас экземплярные свойства прикидываются константами (названы как константы в Java), хотя вызвать их можно только от объекта класса.
Константы удобны тем, что их можно будет использовать во всяких проверках или например в настройках БД, просто вызвав от имени класса.
Здесь же нужно создать экземпляр класса, при этом нужно передать в класс правильное значение, чтобы узнать ограничения значения для этого класса.
Т.е. чтобы узнать ограничения значения нужно исходно знать ограничения из какого-то другого источника (иначе не сможешь создать экземпляр класса).
Эти экземплярные свойства были бы более-менее оправданы в ситуации наличия конструктора по умолчанию, позволяющего создать экземпляр класса без опасности словить исключение, чего здесь быть не может.
Мне кажется в такой ситуации лучше вообще не делать эти экземплярные свойства,
А валидацию делать либо через иерархию конструкторов без использования свойств, либо через валидатор.
Вместо свойств лучше сделать обычные статические константы

2024-11-02 13:32 UTC, merged